import { ArrowRight, Bot, LockKeyhole, MessageSquareText, Mic2, ShieldCheck, Sparkles, WandSparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/button';
import { ApprovedArtwork } from '@/components/marketing/ApprovedArtwork';
import { MarketingFooter, MarketingHeader } from '@/components/marketing/MarketingChrome';

const icons=[Bot,MessageSquareText,Mic2,WandSparkles,LockKeyhole,ShieldCheck];
export default function VelliqoAI(){const {t}=useTranslation(); const features=t('marketingSite.pages.ai.features',{returnObjects:true}) as Array<{title:string;text:string}>; const trust=t('marketingSite.pages.ai.trust',{returnObjects:true}) as string[]; return <div className="min-h-screen overflow-x-hidden bg-[#f7f7fc] text-slate-950"><MarketingHeader active="ai" dark/><main>
<section className="relative overflow-hidden bg-[#0d0b18] text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_12%_10%,rgba(124,58,237,.38),transparent_32%),radial-gradient(circle_at_86%_8%,rgba(217,70,239,.22),transparent_28%)]"/><div className="relative mx-auto grid max-w-[1340px] items-center gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[.85fr_1.15fr] lg:px-8 lg:py-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-violet-300/20 bg-violet-400/10 px-3 py-1.5 text-xs font-extrabold text-violet-200"><Sparkles className="h-4 w-4"/>{t('marketingSite.pages.ai.badge')}</div><h1 className="mt-7 text-4xl font-extrabold leading-[1.02] tracking-[-.05em] sm:text-5xl lg:text-6xl">{t('marketingSite.pages.ai.title')}</h1><p className="mt-6 max-w-xl text-base leading-7 text-white/62 sm:text-lg">{t('marketingSite.pages.ai.text')}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-12 rounded-xl bg-white px-6 text-slate-950 hover:bg-white/90"><Link to="/business-types">{t('marketingSite.pages.ai.cta')}<ArrowRight className="ml-2 h-4 w-4"/></Link></Button><Button asChild size="lg" variant="outline" className="h-12 rounded-xl border-white/15 bg-white/[.04] text-white hover:bg-white/[.08]"><Link to="/experience">{t('marketingSite.pages.ai.secondary')}</Link></Button></div><div className="mt-8 flex flex-wrap gap-2">{trust.map(x=><span key={x} className="rounded-full border border-white/10 bg-white/[.055] px-3 py-1.5 text-xs font-bold text-white/60">{x}</span>)}</div></div><div className="rounded-[2rem] border border-white/10 bg-white/[.045] p-5 shadow-[0_40px_120px_rgba(0,0,0,.4)]"><ApprovedArtwork src="/marketing/approved/velliqo-ai-laptop-transparent.png" alt="Velliqo AI" loading="eager" className="max-w-[800px]"/></div></div></section>
<section className="mx-auto max-w-[1340px] px-4 py-20 sm:px-6 lg:px-8 lg:py-28"><div className="mx-auto max-w-3xl text-center"><div className="text-xs font-extrabold uppercase tracking-[.22em] text-violet-600">{t('marketingSite.pages.ai.sectionEyebrow')}</div><h2 className="mt-4 text-3xl font-extrabold tracking-[-.04em] sm:text-4xl">{t('marketingSite.pages.ai.sectionTitle')}</h2><p className="mt-4 text-sm leading-6 text-slate-600 sm:text-base">{t('marketingSite.pages.ai.sectionText')}</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{features.map((f,i)=>{const Icon=icons[i]||Sparkles;return <article key={f.title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-[0_14px_45px_rgba(15,23,42,.055)]"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-violet-100 text-violet-700"><Icon className="h-5 w-5"/></div><h3 className="mt-5 text-lg font-extrabold">{f.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{f.text}</p></article>})}</div></section>
<section className="bg-slate-950 text-white"><div className="mx-auto max-w-4xl px-4 py-16 text-center sm:px-6 lg:py-20"><Sparkles className="mx-auto h-9 w-9 text-violet-300"/><h2 className="mt-5 text-3xl font-extrabold sm:text-4xl">{t('marketingSite.pages.ai.bottomTitle')}</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 text-white/70">{t('marketingSite.pages.ai.bottomText')}</p><Button asChild size="lg" className="mt-7 h-12 rounded-xl bg-white px-6 text-slate-950 hover:bg-white/90"><Link to="/experience">{t('marketingSite.pages.ai.bottomCta')}<ArrowRight className="ml-2 h-4 w-4"/></Link></Button></div></section>
</main><MarketingFooter/></div>}
