import React from 'react';
import { useLocation } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import {
  Activity,
  BarChart3,
  CalendarDays,
  CheckCircle2,
  CircleDollarSign,
  Clock3,
  CreditCard,
  ImagePlus,
  Layers3,
  Megaphone,
  Package,
  Plus,
  ReceiptText,
  Send,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Users,
  WalletCards,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';
import { useDemoOwner } from '@/demo/DemoOwnerContext';
import PublicCourses from '@/pages/marketing/Courses';

const MODULE_KEYS = ['home','calendar','sales','finance','customers','staff','services','products','marketing','posts','gallery','storefront','business','reports','billing','ai'] as const;

type DemoModuleKey = typeof MODULE_KEYS[number];

export default function DemoModulePage() {
  const location = useLocation();
  const key = location.pathname === '/demo' ? 'home' : location.pathname.split('/')[2] || 'home';
  if (key === 'training' || key === 'courses') return <PublicCourses embedded />;
  return <DemoModule moduleKey={(MODULE_KEYS.includes(key as DemoModuleKey) ? key : 'home') as DemoModuleKey} />;
}

function DemoModule({ moduleKey }: { moduleKey: DemoModuleKey }) {
  const { t } = useTranslation();
  const data = useDemoOwner();
  const [dialog, setDialog] = React.useState<string | null>(null);

  React.useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    if (params.get('action') === 'new' && moduleKey === 'calendar') setDialog('appointment');
  }, [moduleKey]);

  const title = String(t(`demoPage.modules.${moduleKey}.0`));
  const description = String(t(`demoPage.modules.${moduleKey}.1`));
  const action = actionFor(moduleKey, data, setDialog, t);

  return (
    <div className="mx-auto max-w-[1500px] space-y-6">
      <section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <div className="text-[11px] font-extrabold uppercase tracking-[.18em] text-violet-600">{t('demoPage.eyebrow')}</div>
          <h1 className="mt-1 text-3xl font-extrabold tracking-[-.04em] text-foreground sm:text-4xl">{moduleKey === 'home' ? `${title}, ${data.scenario.businessName}` : title}</h1>
          <p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{description}</p>
        </div>
        {action && <Button type="button" className="h-11 rounded-xl" onClick={action.onClick}><action.icon className="mr-2 h-4 w-4" />{action.label}</Button>}
      </section>

      {moduleKey === 'home' && <HomeModule />}
      {moduleKey === 'calendar' && <CalendarModule />}
      {moduleKey === 'sales' && <SalesModule />}
      {moduleKey === 'finance' && <FinanceModule />}
      {moduleKey === 'customers' && <CustomersModule />}
      {moduleKey === 'staff' && <StaffModule />}
      {moduleKey === 'services' && <ServicesModule />}
      {moduleKey === 'products' && <ProductsModule />}
      {moduleKey === 'marketing' && <MarketingModule />}
      {moduleKey === 'posts' && <PostsModule />}
      {moduleKey === 'gallery' && <GalleryModule />}
      {moduleKey === 'storefront' && <StorefrontModule />}
      {moduleKey === 'business' && <BusinessModule />}
      {moduleKey === 'reports' && <ReportsModule />}
      {moduleKey === 'billing' && <BillingModule />}
      {moduleKey === 'ai' && <AIModule />}

      <DemoActionDialog type={dialog} onClose={() => setDialog(null)} />
    </div>
  );
}

function actionFor(moduleKey: DemoModuleKey, data: ReturnType<typeof useDemoOwner>, setDialog: (value: string | null) => void, t: any) {
  const map: Partial<Record<DemoModuleKey, { label: string; icon: typeof Plus; onClick: () => void }>> = {
    calendar: { label: t('demoPage.actions.calendar'), icon: Plus, onClick: () => setDialog('appointment') },
    customers: { label: t('demoPage.actions.customers'), icon: Plus, onClick: () => setDialog('customer') },
    staff: { label: t('demoPage.actions.staff'), icon: Plus, onClick: () => setDialog('staff') },
    services: { label: t('demoPage.actions.services'), icon: Plus, onClick: () => setDialog('service') },
    products: { label: t('demoPage.actions.products'), icon: Package, onClick: data.adjustStock },
    sales: { label: t('demoPage.actions.sales'), icon: ShoppingCart, onClick: data.addSale },
    marketing: { label: t('demoPage.actions.marketing'), icon: Megaphone, onClick: data.addCampaign },
    posts: { label: t('demoPage.actions.posts'), icon: Plus, onClick: data.addPost },
    gallery: { label: t('demoPage.actions.gallery'), icon: ImagePlus, onClick: data.addGalleryItem },
  };
  return map[moduleKey];
}

function HomeModule() {
  const { t } = useTranslation();
  const d = useDemoOwner();
  const metrics = [
    [t('demoPage.home.todayAppointments'), d.appointments.length, CalendarDays],
    [t('demoPage.home.expectedRevenue'), `${d.scenario.currency}${Math.round(d.scenario.metrics.revenue + d.sales.reduce((sum, sale) => sum + sale.total, 0) / 4)}`, CircleDollarSign],
    [t('demoPage.home.activeCustomers'), d.customers.length, Users],
    [t('demoPage.home.teamUtilisation'), `${Math.round(d.team.reduce((sum, member) => sum + member.utilisation, 0) / d.team.length)}%`, Activity],
  ] as const;
  return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,Icon])=><MetricCard key={String(label)} label={String(label)} value={value} icon={Icon}/>)}</section><section className="grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,.55fr)]"><Panel title={t('demoPage.home.todaySchedule')} subtitle={t('demoPage.home.todayScheduleSub')}><AppointmentList limit={6}/></Panel><div className="space-y-5"><Panel title={t('demoPage.home.briefing')} subtitle={t('demoPage.home.briefingSub')}><div className="rounded-2xl bg-gradient-to-br from-violet-700 to-fuchsia-600 p-5 text-white"><div className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.18em] text-white/65"><Sparkles className="h-4 w-4"/>{t('demoPage.home.businessIntelligence')}</div><p className="mt-4 text-sm leading-6 text-white/82">{d.scenario.aiResponse}</p></div></Panel><Panel title={t('demoPage.home.health')} subtitle={t('demoPage.home.healthSub')}><div className="flex items-center justify-between"><div><div className="text-4xl font-extrabold">82<span className="text-lg text-muted-foreground">/100</span></div><p className="mt-2 text-xs text-muted-foreground">{t('demoPage.home.healthText')}</p></div><div className="flex h-20 w-20 items-center justify-center rounded-full border-[10px] border-emerald-200 text-lg font-extrabold text-emerald-700">82</div></div></Panel></div></section></>;
}

function CalendarModule() { const {t}=useTranslation(); return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><Panel title={t('demoPage.calendar.week')} subtitle={t('demoPage.calendar.weekSub')}><div className="grid grid-cols-[70px_repeat(3,minmax(130px,1fr))] overflow-x-auto rounded-xl border"><div className="bg-muted/50 p-3 text-xs font-bold">{t('demoPage.common.time')}</div>{[1,2,3].map((n)=><div key={n} className="border-l bg-muted/50 p-3 text-center text-xs font-bold">{t('demoPage.calendar.professional',{count:n})}</div>)}{['09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00'].map((time,row)=><React.Fragment key={time}><div className="border-t p-3 text-xs font-bold">{time}</div>{[0,1,2].map((col)=><div key={col} className="min-h-16 border-l border-t p-1.5">{(row+col)%4===0&&<div className="rounded-lg border border-emerald-300 bg-emerald-100 p-2 text-[10px] font-bold text-emerald-900">{t('demoPage.calendar.confirmed')}</div>}</div>)}</React.Fragment>)}</div></Panel><Panel title={t('demoPage.common.appointments')} subtitle={t('demoPage.calendar.session')}><AppointmentList/></Panel></div>; }
function SalesModule() { const {t}=useTranslation(); const d=useDemoOwner(); return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><Panel title={t('demoPage.sales.recent')} subtitle={t('demoPage.sales.recentSub')}><div className="divide-y">{d.sales.map((sale)=><div key={sale.id} className="grid grid-cols-[1fr_auto] gap-3 py-4"><div><div className="text-sm font-extrabold">{sale.reference}</div><div className="text-xs text-muted-foreground">{sale.customer}</div></div><div className="text-right"><div className="text-sm font-extrabold">{d.scenario.currency}{sale.total.toFixed(2)}</div><span className="text-[10px] font-bold uppercase text-emerald-700">{sale.status}</span></div></div>)}</div></Panel><Panel title={t('demoPage.sales.checkout')} subtitle={t('demoPage.sales.checkoutSub')}><div className="space-y-3 rounded-2xl bg-muted/50 p-4 text-sm"><div className="flex justify-between"><span>{t('demoPage.sales.selectedService')}</span><strong>{d.services[0]?.name}</strong></div><div className="flex justify-between"><span>{t('demoPage.sales.subtotal')}</span><strong>{d.scenario.currency}{d.services[0]?.price.toFixed(2)}</strong></div><div className="flex justify-between border-t pt-3 text-base"><span>{t('demoPage.sales.total')}</span><strong>{d.scenario.currency}{d.services[0]?.price.toFixed(2)}</strong></div></div></Panel></div>; }
function FinanceModule() { const {t}=useTranslation(); const d=useDemoOwner(); return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label={t('demoPage.common.revenue')} value={`${d.scenario.currency}${d.scenario.metrics.revenue}`} icon={CircleDollarSign}/><MetricCard label={t('demoPage.common.expenses')} value={`${d.scenario.currency}184`} icon={ReceiptText}/><MetricCard label={t('demoPage.common.netResult')} value={`${d.scenario.currency}${d.scenario.metrics.revenue-184}`} icon={WalletCards}/><MetricCard label={t('demoPage.common.transactions')} value={d.sales.length+8} icon={CreditCard}/></section><Panel title={t('demoPage.finance.cashFlow')} subtitle={t('demoPage.finance.cashFlowSub')}><div className="flex h-72 items-end gap-4 rounded-2xl bg-muted/40 p-5">{[42,58,47,76,62,88,71].map((height,i)=><div key={i} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-xl bg-gradient-to-t from-violet-700 to-violet-400" style={{height:`${height}%`}}/><span className="text-[10px] text-muted-foreground">{t('demoPage.common.day')} {i+1}</span></div>)}</div></Panel></>; }
function CustomersModule() { const {t}=useTranslation(); const d=useDemoOwner(); return <Panel title={t('demoPage.customers.directory')} subtitle={t('demoPage.customers.directorySub')}><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b bg-muted/40 text-xs text-muted-foreground"><tr><th className="p-3">{t('demoPage.common.customer')}</th><th className="p-3">{t('demoPage.common.contact')}</th><th className="p-3">{t('demoPage.common.lastVisit')}</th><th className="p-3">{t('demoPage.common.visits')}</th><th className="p-3">{t('demoPage.common.lifetimeValue')}</th></tr></thead><tbody className="divide-y">{d.customers.map((customer)=><tr key={customer.id}><td className="p-3 font-bold">{customer.name}</td><td className="p-3"><div>{customer.email}</div><div className="text-xs text-muted-foreground">{customer.phone}</div></td><td className="p-3">{customer.lastVisit}</td><td className="p-3">{customer.visits}</td><td className="p-3 font-bold">{d.scenario.currency}{customer.value}</td></tr>)}</tbody></table></div></Panel>; }
function StaffModule() { const {t}=useTranslation(); const d=useDemoOwner(); return <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{d.team.map((member)=><article key={member.id} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-100 font-extrabold text-violet-700">{member.name.charAt(0)}</div><div><h2 className="font-extrabold">{member.name}</h2><p className="text-xs text-muted-foreground">{member.role}</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><div className="rounded-xl bg-muted/50 p-3"><span className="text-muted-foreground">{t('demoPage.common.hours')}</span><div className="mt-1 font-bold">{member.workingHours}</div></div><div className="rounded-xl bg-muted/50 p-3"><span className="text-muted-foreground">{t('demoPage.common.utilisation')}</span><div className="mt-1 font-bold">{member.utilisation}%</div></div></div></article>)}</section>; }
function ServicesModule() { const {t}=useTranslation(); const d=useDemoOwner(); return <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{d.services.map((service)=><article key={service.id} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-amber-100 text-amber-700"><Layers3 className="h-5 w-5"/></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold uppercase text-emerald-700">{t('demoPage.common.active')}</span></div><h2 className="mt-5 text-lg font-extrabold">{service.name}</h2><div className="mt-3 flex gap-4 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5"/>{service.duration} min</span><span className="font-extrabold text-foreground">{d.scenario.currency}{service.price}</span></div></article>)}</section>; }
function ProductsModule() { const {t}=useTranslation(); const d=useDemoOwner(); return <Panel title={t('demoPage.products.inventory')} subtitle={t('demoPage.products.inventorySub')}><div className="grid gap-3">{d.products.map((product)=><div key={product.id} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-[minmax(0,1fr)_120px_120px]"><div><div className="font-extrabold">{product.name}</div><div className="text-xs text-muted-foreground">{t('demoPage.common.threshold')} {product.threshold}</div></div><div><div className="text-xs text-muted-foreground">{t('demoPage.common.stock')}</div><div className={cn('font-extrabold',product.stock<=product.threshold?'text-rose-600':'text-emerald-700')}>{product.stock} {t('demoPage.common.units')}</div></div><div><div className="text-xs text-muted-foreground">{t('demoPage.common.retailPrice')}</div><div className="font-extrabold">{d.scenario.currency}{product.price}</div></div></div>)}</div></Panel>; }
function MarketingModule() { const {t}=useTranslation(); const d=useDemoOwner(); const rules=t('demoPage.marketing.rules',{returnObjects:true}) as string[]; return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><Panel title={t('demoPage.marketing.campaigns')} subtitle={t('demoPage.marketing.campaignsSub')}><div className="grid gap-3">{d.campaigns.map((campaign)=><div key={campaign.id} className="flex items-center justify-between rounded-xl border p-4"><div><div className="font-extrabold">{campaign.name}</div><div className="text-xs text-muted-foreground">{t('demoPage.common.audience')}: {campaign.audience} {t('demoPage.common.customers')}</div></div><span className={cn('rounded-full px-2.5 py-1 text-[10px] font-bold uppercase',campaign.status==='draft'?'bg-amber-100 text-amber-800':'bg-violet-100 text-violet-700')}>{campaign.status}</span></div>)}</div></Panel><Panel title={t('demoPage.marketing.controls')} subtitle={t('demoPage.marketing.controlsSub')}><StatusRow label={t('demoPage.marketing.appointmentEmail')} value={d.settings.reminders?t('demoPage.common.enabled'):t('demoPage.common.disabled')}/><StatusRow label={t('demoPage.marketing.emailReminders')} value={d.settings.reminders?t('demoPage.common.enabled'):t('demoPage.common.disabled')}/><StatusRow label={t('demoPage.marketing.smsProvider')} value={t('demoPage.common.notConnected')}/><div className="mt-4"><ul className="space-y-3 text-sm text-muted-foreground">{rules.map((item)=><li key={item} className="flex gap-2"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600"/>{item}</li>)}</ul></div></Panel></div>; }
function PostsModule() { const {t}=useTranslation(); const d=useDemoOwner(); return <Panel title={t('demoPage.posts.title')} subtitle={t('demoPage.posts.subtitle')}><div className="grid gap-4 md:grid-cols-2">{d.posts.map((post)=><article key={post.id} className="rounded-2xl border p-5"><div className="flex items-center justify-between"><Megaphone className="h-5 w-5 text-violet-600"/><span className="rounded-full bg-muted px-2 py-1 text-[10px] font-bold uppercase">{post.status}</span></div><h2 className="mt-4 font-extrabold">{post.title}</h2><p className="mt-2 text-xs text-muted-foreground">{t('demoPage.common.created')} {post.createdAt}</p></article>)}</div></Panel>; }
function GalleryModule() { const {t}=useTranslation(); const d=useDemoOwner(); return <Panel title={t('demoPage.gallery.title')} subtitle={t('demoPage.gallery.subtitle',{count:d.galleryCount})}><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{Array.from({length:d.galleryCount}).map((_,index)=><div key={index} className="aspect-square overflow-hidden rounded-2xl border bg-gradient-to-br from-violet-100 via-white to-amber-100"><div className="flex h-full items-center justify-center"><ImagePlus className="h-8 w-8 text-violet-400"/></div></div>)}</div></Panel>; }
function StorefrontModule() { const {t}=useTranslation(); const d=useDemoOwner(); return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><Panel title={t('demoPage.storefront.preview')} subtitle={t('demoPage.storefront.previewSub')}><div className="overflow-hidden rounded-2xl border bg-slate-950 text-white"><div className="bg-[radial-gradient(circle_at_top_right,_rgba(124,58,237,.45),_transparent_45%)] p-7"><div className="text-xs font-bold uppercase tracking-[.16em] text-violet-300">{d.scenario.industry}</div><h2 className="mt-3 text-3xl font-extrabold">{d.scenario.businessName}</h2><p className="mt-3 max-w-xl text-sm text-white/65">{t('demoPage.storefront.hero')}</p><Button className="mt-6 rounded-xl bg-amber-400 text-slate-950 hover:bg-amber-300">{t('demoPage.storefront.book')}</Button></div></div></Panel><Panel title={t('demoPage.storefront.controls')} subtitle={t('demoPage.storefront.controlsSub')}><StatusRow label={t('demoPage.storefront.publicPage')} value={t('demoPage.common.published')}/><StatusRow label={t('demoPage.common.onlineBooking')} value={d.settings.onlineBooking?t('demoPage.common.enabled'):t('demoPage.common.disabled')}/><StatusRow label={t('demoPage.storefront.bookingRules')} value={t('demoPage.common.configured')}/><StatusRow label={t('demoPage.storefront.servicesVisible')} value={String(d.services.length)}/><StatusRow label={t('demoPage.storefront.galleryImages')} value={String(d.galleryCount)}/></Panel></div>; }
function BusinessModule() { const {t}=useTranslation(); const d=useDemoOwner(); return <div className="grid gap-5 lg:grid-cols-2"><Panel title={t('demoPage.business.profile')} subtitle={t('demoPage.business.profileSub')}><Field label={t('demoPage.common.businessName')} value={d.scenario.businessName}/><Field label={t('demoPage.common.industry')} value={d.scenario.industry}/><Field label={t('demoPage.common.region')} value="Nicosia, Cyprus"/><Field label={t('demoPage.common.timezone')} value="Europe/Nicosia"/></Panel><Panel title={t('demoPage.business.operations')} subtitle={t('demoPage.business.operationsSub')}><StatusRow label={t('demoPage.common.onlineBooking')} value={t('demoPage.common.enabled')}/><StatusRow label={t('demoPage.common.businessClosures')} value={t('demoPage.common.noneConfigured')}/><StatusRow label={t('demoPage.common.guestBookings')} value={t('demoPage.common.allowed')}/><StatusRow label={t('demoPage.common.defaultCurrency')} value={d.scenario.currency}/></Panel></div>; }
function ReportsModule() { const {t}=useTranslation(); const d=useDemoOwner(); return <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label={t('demoPage.common.revenue')} value={`${d.scenario.currency}${d.scenario.metrics.revenue}`} icon={CircleDollarSign}/><MetricCard label={t('demoPage.common.appointments')} value={d.appointments.length} icon={CalendarDays}/><MetricCard label={t('demoPage.common.completionRate')} value="76%" icon={CheckCircle2}/><MetricCard label={t('demoPage.common.newCustomers')} value={d.customers.length} icon={Users}/></section><Panel title={t('demoPage.reports.trend')} subtitle={t('demoPage.reports.trendSub')}><div className="flex h-72 items-end gap-3 rounded-2xl border bg-muted/30 p-5">{[35,48,44,63,58,82,74,91,68,88].map((height,index)=><div key={index} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-lg bg-violet-600" style={{height:`${height}%`}}/><span className="text-[9px] text-muted-foreground">{index+1}</span></div>)}</div></Panel></>; }
function BillingModule() { const {t}=useTranslation(); return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><Panel title={t('demoPage.billing.title')} subtitle={t('demoPage.billing.subtitle')}><div className="rounded-2xl border border-violet-200 bg-violet-50 p-5"><div className="flex items-center justify-between"><div><div className="text-xs font-bold uppercase tracking-[.16em] text-violet-700">{t('demoPage.common.currentPlan')}</div><h2 className="mt-2 text-2xl font-extrabold text-violet-950">{t('demoPage.billing.professional')}</h2></div><CreditCard className="h-8 w-8 text-violet-600"/></div><div className="mt-5 text-3xl font-extrabold">€59.99<span className="text-sm font-semibold text-muted-foreground"> {t('demoPage.common.perMonth')}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs font-bold"><div className="rounded-xl border bg-white/70 p-2">Standard<br/>€34.99</div><div className="rounded-xl border border-violet-300 bg-white p-2 text-violet-800">Professional<br/>€59.99</div><div className="rounded-xl border bg-white/70 p-2">Premium<br/>€100.99</div></div></div></Panel><Panel title={t('demoPage.common.invoices')} subtitle={t('demoPage.billing.historySub')}><div className="space-y-3">{['July 2026','June 2026','May 2026'].map((month)=><StatusRow key={month} label={month} value={`${t('demoPage.common.paid')} - €59.99`}/>)}</div></Panel></div>; }
function AIModule() { const {t}=useTranslation(); const d=useDemoOwner(); const [messages,setMessages]=React.useState([{role:'assistant',text:t('demoPage.ai.initial',{business:d.scenario.businessName})}]); const [input,setInput]=React.useState(''); const [confirm,setConfirm]=React.useState(false); const ask=()=>{if(!input.trim())return; const text=input.trim(); setMessages((m)=>[...m,{role:'user',text},{role:'assistant',text:d.scenario.aiResponse}]); if(/create|add|prepare|send|book/i.test(text))setConfirm(true); setInput('');}; return <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><Panel title={t('demoPage.ai.conversation')} subtitle={t('demoPage.ai.conversationSub')}><div className="flex min-h-[430px] flex-col"><div className="flex-1 space-y-3 overflow-y-auto rounded-2xl bg-muted/30 p-4">{messages.map((m,i)=><div key={i} className={cn('max-w-[85%] rounded-2xl px-4 py-3 text-sm leading-6',m.role==='user'?'ml-auto bg-violet-600 text-white':'bg-white shadow-sm')}>{m.text}</div>)}</div><div className="mt-3 flex gap-2"><Input value={input} onChange={(e)=>setInput(e.target.value)} onKeyDown={(e)=>e.key==='Enter'&&ask()} placeholder={t('demoPage.ai.placeholder')}/><Button size="icon" onClick={ask}><Send className="h-4 w-4"/></Button></div></div></Panel><Panel title={t('demoPage.ai.permissions')} subtitle={t('demoPage.ai.permissionsSub')}><div className="space-y-3"><StatusRow label={t('demoPage.ai.read')} value={t('demoPage.ai.readValue')}/><StatusRow label={t('demoPage.ai.draft')} value={t('demoPage.ai.draftValue')}/><StatusRow label={t('demoPage.ai.campaign')} value={t('demoPage.ai.demoDisabled')}/><StatusRow label={t('demoPage.ai.delete')} value={t('demoPage.ai.demoDisabled')}/></div></Panel><Dialog open={confirm} onOpenChange={setConfirm}><DialogContent><DialogHeader><DialogTitle>{t('demoPage.ai.confirmTitle')}</DialogTitle><DialogDescription>{t('demoPage.ai.confirmText')}</DialogDescription></DialogHeader><div className="rounded-xl border bg-muted/40 p-4 text-sm"><strong>{t('demoPage.ai.prepared')}</strong> {t('demoPage.ai.preparedText')}</div><DialogFooter><Button variant="outline" onClick={()=>setConfirm(false)}>{t('demoPage.common.cancel')}</Button><Button onClick={()=>{setConfirm(false);setMessages((m)=>[...m,{role:'assistant',text:t('demoPage.ai.confirmed')}]);}}>{t('demoPage.ai.confirmTitle')}</Button></DialogFooter></DialogContent></Dialog></div>; }
function DemoActionDialog({type,onClose}:{type:string|null;onClose:()=>void}) { const {t}=useTranslation(); const d=useDemoOwner(); const configs:Record<string,{title:string;description:string;action:()=>void}>={appointment:{title:t('demoPage.dialog.appointmentTitle'),description:t('demoPage.dialog.appointmentText'),action:d.addAppointment},customer:{title:t('demoPage.dialog.customerTitle'),description:t('demoPage.dialog.customerText'),action:d.addCustomer},staff:{title:t('demoPage.dialog.staffTitle'),description:t('demoPage.dialog.staffText'),action:d.addTeamMember},service:{title:t('demoPage.dialog.serviceTitle'),description:t('demoPage.dialog.serviceText'),action:d.addService}}; const config=type?configs[type]:null; return <Dialog open={Boolean(config)} onOpenChange={(open)=>!open&&onClose()}>{config&&<DialogContent><DialogHeader><DialogTitle>{config.title}</DialogTitle><DialogDescription>{config.description}</DialogDescription></DialogHeader><div className="grid gap-3"><Input defaultValue={type==='appointment'?t('demoPage.dialog.demoCustomer'):type==='service'?t('demoPage.dialog.demoService'):t('demoPage.dialog.sampleValue')}/><Input defaultValue={type==='appointment'?'16:30':type==='service'?t('demoPage.dialog.minutes'):t('demoPage.dialog.additional')}/></div><div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-900"><ShieldCheck className="mr-2 inline h-4 w-4"/>{t('demoPage.dialog.safety')}</div><DialogFooter><Button variant="outline" onClick={onClose}>{t('demoPage.common.cancel')}</Button><Button onClick={()=>{config.action();onClose();}}>{t('demoPage.common.apply')}</Button></DialogFooter></DialogContent>}</Dialog>; }
function MetricCard({label,value,icon:Icon}:{label:string;value:React.ReactNode;icon:typeof BarChart3}) { return <article className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-bold text-muted-foreground">{label}</span><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-4 w-4"/></span></div><div className="mt-4 text-2xl font-extrabold">{value}</div></article>; }
function Panel({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}) { return <section className="rounded-2xl border bg-card p-4 shadow-sm sm:p-5"><div className="mb-4 flex items-start justify-between gap-3"><div><h2 className="font-extrabold">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</div></div>{children}</section>; }
function AppointmentList({limit}:{limit?:number}) { const d=useDemoOwner(); return <div className="grid gap-2">{d.appointments.slice(0,limit).map((appointment)=><div key={appointment.id} className="grid grid-cols-[58px_minmax(0,1fr)_auto] items-center gap-3 rounded-xl border bg-muted/25 p-3"><div className="text-xs font-extrabold">{appointment.time}</div><div className="min-w-0"><div className="truncate text-sm font-extrabold">{appointment.customer}</div><div className="truncate text-xs text-muted-foreground">{appointment.service} - {appointment.professional}</div></div><span className="rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold text-emerald-700">{appointment.status}</span></div>)}</div>; }
function StatusRow({label,value}:{label:string;value:string}) { return <div className="flex items-center justify-between gap-4 border-b py-3 text-sm last:border-0"><span className="text-muted-foreground">{label}</span><strong className="text-right">{value}</strong></div>; }
function Field({label,value}:{label:string;value:string}) { return <label className="mb-4 block"><span className="mb-1.5 block text-xs font-bold text-muted-foreground">{label}</span><Input value={value} readOnly/></label>; }
