-- 00037_velliqo_ai_secure_action_engine.sql
-- Secure, confirmation-based action execution for Velliqo AI.
--
-- The AI may prepare an action request, but only an authenticated Owner or
-- Manager can execute it through the RPC below. Every execution is validated,
-- tenant-scoped, idempotent, audited and performed server-side.

begin;

alter table public.ai_action_requests
  add column if not exists conversation_id uuid references public.ai_conversations(id) on delete set null,
  add column if not exists source_message_id uuid references public.ai_messages(id) on delete set null,
  add column if not exists message_id uuid references public.ai_messages(id) on delete set null,
  add column if not exists title text,
  add column if not exists summary text,
  add column if not exists risk_level text not null default 'medium',
  add column if not exists preview jsonb not null default '{}'::jsonb,
  add column if not exists execution_result jsonb,
  add column if not exists idempotency_key text,
  add column if not exists expires_at timestamptz,
  add column if not exists execution_started_at timestamptz,
  add column if not exists action_version integer not null default 1;

do $$
begin
  alter table public.ai_action_requests
    add constraint ai_action_requests_risk_level_check
    check (risk_level in ('low', 'medium', 'high'));
exception
  when duplicate_object then null;
end;
$$;

create unique index if not exists ai_action_requests_idempotency_uidx
  on public.ai_action_requests (business_id, idempotency_key)
  where idempotency_key is not null;

create index if not exists ai_action_requests_conversation_idx
  on public.ai_action_requests (conversation_id, created_at desc);

create index if not exists ai_action_requests_pending_idx
  on public.ai_action_requests (business_id, status, expires_at, created_at desc);

-- Action requests are generated by the trusted Edge Function. Browser clients
-- can read them but cannot insert or update them directly.
drop policy if exists "Members create AI action requests" on public.ai_action_requests;
drop policy if exists "Owners approve AI action requests" on public.ai_action_requests;
drop policy if exists "Members read AI action requests" on public.ai_action_requests;
drop policy if exists "Authorized users read AI action requests" on public.ai_action_requests;

create policy "Authorized users read AI action requests"
on public.ai_action_requests
for select
to authenticated
using (
  requested_by = auth.uid()
  or exists (
    select 1
    from public.business_members bm
    where bm.business_id = ai_action_requests.business_id
      and bm.user_id = auth.uid()
      and bm.role::text in ('Owner', 'Manager')
  )
);

revoke insert, update, delete on public.ai_action_requests from authenticated;
grant select on public.ai_action_requests to authenticated;
grant all on public.ai_action_requests to service_role;

create or replace function public.execute_ai_action_request(
  p_business_id uuid,
  p_action_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_role text;
  v_action public.ai_action_requests%rowtype;
  v_settings public.ai_settings%rowtype;
  v_payload jsonb;
  v_result jsonb := '{}'::jsonb;
  v_customer_id uuid;
  v_employee_id uuid;
  v_service_ids uuid[];
  v_appointment_id uuid;
  v_email text;
  v_phone text;
  v_name text;
  v_normalized_phone text;
  v_reason text;
begin
  if v_user_id is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  select bm.role::text
    into v_role
  from public.business_members bm
  where bm.business_id = p_business_id
    and bm.user_id = v_user_id
  limit 1;

  if v_role not in ('Owner', 'Manager') then
    raise exception using errcode = '42501', message = 'Only an owner or manager can confirm AI actions.';
  end if;

  select *
    into v_settings
  from public.ai_settings
  where business_id = p_business_id;

  if not found or v_settings.enabled is false then
    raise exception using errcode = '42501', message = 'Velliqo AI is disabled for this business.';
  end if;

  if coalesce(v_settings.allow_write_actions, false) is false then
    raise exception using errcode = '42501', message = 'AI write actions are disabled in Velliqo AI settings.';
  end if;

  select *
    into v_action
  from public.ai_action_requests
  where id = p_action_id
    and business_id = p_business_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'AI action request not found.';
  end if;

  if v_action.status = 'executed' then
    return jsonb_build_object(
      'success', true,
      'status', 'executed',
      'action_id', v_action.id,
      'action_type', v_action.action_type,
      'result', coalesce(v_action.execution_result, '{}'::jsonb),
      'idempotent_replay', true
    );
  end if;

  if v_action.status <> 'pending' then
    raise exception using errcode = '22023', message = 'This AI action is no longer pending confirmation.';
  end if;

  if coalesce(v_action.expires_at, v_action.created_at + interval '30 minutes') < now() then
    update public.ai_action_requests
    set status = 'rejected',
        error_message = 'The confirmation window expired.',
        updated_at = now()
    where id = v_action.id;

    if v_action.message_id is not null then
      update public.ai_messages
      set metadata = jsonb_set(
        jsonb_set(
          coalesce(metadata, '{}'::jsonb),
          '{pending_action,status}',
          to_jsonb('rejected'::text),
          true
        ),
        '{pending_action,error_message}',
        to_jsonb('The confirmation window expired.'::text),
        true
      )
      where id = v_action.message_id
        and business_id = p_business_id;
    end if;

    return jsonb_build_object(
      'success', false,
      'status', 'rejected',
      'action_id', v_action.id,
      'error', 'The confirmation window expired.'
    );
  end if;

  v_payload := coalesce(v_action.payload, '{}'::jsonb);

  update public.ai_action_requests
  set status = 'approved',
      approved_by = v_user_id,
      approved_at = now(),
      execution_started_at = now(),
      error_message = null,
      updated_at = now()
  where id = v_action.id;

  begin
    if v_action.action_type = 'create_customer' then
      v_name := nullif(btrim(v_payload->>'full_name'), '');
      v_email := nullif(lower(btrim(v_payload->>'email')), '');
      v_phone := nullif(btrim(v_payload->>'phone'), '');
      v_normalized_phone := regexp_replace(coalesce(v_phone, ''), '\D', '', 'g');

      if v_name is null then
        raise exception using errcode = '22023', message = 'Customer name is required.';
      end if;

      if v_email is null and v_phone is null then
        raise exception using errcode = '22023', message = 'Customer email or phone is required.';
      end if;

      if v_email is not null then
        select c.id into v_customer_id
        from public.customers c
        where c.business_id = p_business_id
          and lower(c.email) = v_email
        order by c.created_at
        limit 1;
      end if;

      if v_customer_id is null and v_normalized_phone <> '' then
        select c.id into v_customer_id
        from public.customers c
        where c.business_id = p_business_id
          and lower(btrim(c.full_name)) = lower(v_name)
          and regexp_replace(coalesce(c.phone, ''), '\D', '', 'g') = v_normalized_phone
        order by c.created_at
        limit 1;
      end if;

      if v_customer_id is null then
        insert into public.customers (
          business_id,
          full_name,
          email,
          phone,
          notes
        ) values (
          p_business_id,
          v_name,
          v_email,
          v_phone,
          nullif(btrim(v_payload->>'notes'), '')
        )
        returning id into v_customer_id;
      end if;

      v_result := jsonb_build_object(
        'customer_id', v_customer_id,
        'full_name', v_name
      );

    elsif v_action.action_type = 'create_appointment' then
      v_customer_id := nullif(v_payload->>'customer_id', '')::uuid;

      if v_customer_id is not null and not exists (
        select 1 from public.customers c
        where c.id = v_customer_id and c.business_id = p_business_id
      ) then
        raise exception using errcode = '22023', message = 'The selected customer does not belong to this business.';
      end if;

      if v_customer_id is null then
        v_name := nullif(btrim(v_payload->>'customer_name'), '');
        v_email := nullif(lower(btrim(v_payload->>'customer_email')), '');
        v_phone := nullif(btrim(v_payload->>'customer_phone'), '');
        v_normalized_phone := regexp_replace(coalesce(v_phone, ''), '\D', '', 'g');

        if v_name is null or v_phone is null then
          raise exception using errcode = '22023', message = 'A customer name and phone are required for a new appointment customer.';
        end if;

        if v_email is not null then
          select c.id into v_customer_id
          from public.customers c
          where c.business_id = p_business_id
            and lower(c.email) = v_email
          order by c.created_at
          limit 1;
        end if;

        if v_customer_id is null and v_normalized_phone <> '' then
          select c.id into v_customer_id
          from public.customers c
          where c.business_id = p_business_id
            and lower(btrim(c.full_name)) = lower(v_name)
            and regexp_replace(coalesce(c.phone, ''), '\D', '', 'g') = v_normalized_phone
          order by c.created_at
          limit 1;
        end if;

        if v_customer_id is null then
          insert into public.customers (
            business_id,
            full_name,
            email,
            phone,
            notes
          ) values (
            p_business_id,
            v_name,
            v_email,
            v_phone,
            nullif(btrim(v_payload->>'customer_notes'), '')
          )
          returning id into v_customer_id;
        end if;
      end if;

      select array_agg(value::uuid)
        into v_service_ids
      from jsonb_array_elements_text(coalesce(v_payload->'service_ids', '[]'::jsonb));

      if v_service_ids is null or cardinality(v_service_ids) = 0 then
        raise exception using errcode = '22023', message = 'At least one service is required.';
      end if;

      v_employee_id := nullif(v_payload->>'employee_id', '')::uuid;

      select public.owner_create_appointment(
        p_business_id,
        v_customer_id,
        v_employee_id,
        v_service_ids,
        (v_payload->>'local_date')::date,
        (v_payload->>'local_time')::time,
        'confirmed'::public.appointment_status,
        nullif(btrim(v_payload->>'notes'), '')
      ) into v_result;

    elsif v_action.action_type = 'reschedule_appointment' then
      v_appointment_id := nullif(v_payload->>'appointment_id', '')::uuid;
      v_employee_id := nullif(v_payload->>'employee_id', '')::uuid;

      select public.owner_reschedule_appointment(
        p_business_id,
        v_appointment_id,
        v_employee_id,
        (v_payload->>'local_date')::date,
        (v_payload->>'local_time')::time
      ) into v_result;

    elsif v_action.action_type = 'cancel_appointment' then
      v_appointment_id := nullif(v_payload->>'appointment_id', '')::uuid;
      v_reason := nullif(btrim(v_payload->>'reason'), '');

      if v_reason is not null then
        update public.appointments
        set notes = concat_ws(E'\n', nullif(notes, ''), 'AI cancellation reason: ' || v_reason),
            updated_at = now()
        where id = v_appointment_id
          and business_id = p_business_id;
      end if;

      select public.owner_update_appointment_status(
        p_business_id,
        v_appointment_id,
        'cancelled_by_business'::public.appointment_status
      ) into v_result;

    elsif v_action.action_type = 'create_campaign_draft' then
      insert into public.marketing_campaigns (
        business_id,
        name,
        channel,
        objective,
        audience_segment,
        subject,
        message,
        status,
        scheduled_at,
        created_by
      ) values (
        p_business_id,
        nullif(btrim(v_payload->>'name'), ''),
        coalesce(nullif(v_payload->>'channel', ''), 'email'),
        coalesce(nullif(v_payload->>'objective', ''), 'custom'),
        coalesce(nullif(v_payload->>'audience_segment', ''), 'all'),
        nullif(btrim(v_payload->>'subject'), ''),
        nullif(btrim(v_payload->>'message'), ''),
        'draft',
        null,
        v_user_id
      )
      returning jsonb_build_object(
        'campaign_id', id,
        'name', name,
        'status', status
      ) into v_result;

    elsif v_action.action_type = 'create_post_draft' then
      insert into public.business_posts (
        business_id,
        author_user_id,
        title,
        content,
        post_type,
        audience,
        is_published,
        published_at,
        expires_at
      ) values (
        p_business_id,
        v_user_id,
        nullif(btrim(v_payload->>'title'), ''),
        nullif(btrim(v_payload->>'content'), ''),
        coalesce(nullif(v_payload->>'post_type', ''), 'announcement'),
        coalesce(nullif(v_payload->>'audience', ''), 'public'),
        false,
        null,
        nullif(v_payload->>'expires_at', '')::timestamptz
      )
      returning jsonb_build_object(
        'post_id', id,
        'title', title,
        'status', 'draft'
      ) into v_result;

    else
      raise exception using errcode = '22023', message = 'Unsupported AI action type.';
    end if;

    update public.ai_action_requests
    set status = 'executed',
        executed_at = now(),
        execution_result = v_result,
        error_message = null,
        updated_at = now()
    where id = v_action.id;

    if v_action.message_id is not null then
      update public.ai_messages
      set metadata = jsonb_set(
        jsonb_set(
          jsonb_set(
            coalesce(metadata, '{}'::jsonb),
            '{pending_action,status}',
            to_jsonb('executed'::text),
            true
          ),
          '{pending_action,execution_result}',
          coalesce(v_result, '{}'::jsonb),
          true
        ),
        '{pending_action,error_message}',
        'null'::jsonb,
        true
      )
      where id = v_action.message_id
        and business_id = p_business_id;
    end if;

    insert into public.audit_logs (business_id, user_id, action, details)
    values (
      p_business_id,
      v_user_id,
      'ai_action_executed',
      jsonb_build_object(
        'ai_action_id', v_action.id,
        'action_type', v_action.action_type,
        'requested_by', v_action.requested_by,
        'approved_by', v_user_id,
        'result', v_result
      )
    );

    return jsonb_build_object(
      'success', true,
      'status', 'executed',
      'action_id', v_action.id,
      'action_type', v_action.action_type,
      'result', v_result,
      'idempotent_replay', false
    );

  exception
    when others then
      update public.ai_action_requests
      set status = 'failed',
          executed_at = now(),
          error_message = sqlerrm,
          execution_result = jsonb_build_object('error', sqlerrm),
          updated_at = now()
      where id = v_action.id;

      if v_action.message_id is not null then
        update public.ai_messages
        set metadata = jsonb_set(
          jsonb_set(
            coalesce(metadata, '{}'::jsonb),
            '{pending_action,status}',
            to_jsonb('failed'::text),
            true
          ),
          '{pending_action,error_message}',
          to_jsonb(sqlerrm),
          true
        )
        where id = v_action.message_id
          and business_id = p_business_id;
      end if;

      insert into public.audit_logs (business_id, user_id, action, details)
      values (
        p_business_id,
        v_user_id,
        'ai_action_failed',
        jsonb_build_object(
          'ai_action_id', v_action.id,
          'action_type', v_action.action_type,
          'error', sqlerrm
        )
      );

      return jsonb_build_object(
        'success', false,
        'status', 'failed',
        'action_id', v_action.id,
        'action_type', v_action.action_type,
        'error', sqlerrm
      );
  end;
end;
$$;

revoke all on function public.execute_ai_action_request(uuid, uuid) from public;
grant execute on function public.execute_ai_action_request(uuid, uuid) to authenticated;

create or replace function public.reject_ai_action_request(
  p_business_id uuid,
  p_action_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_role text;
  v_action public.ai_action_requests%rowtype;
begin
  if v_user_id is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  select bm.role::text
    into v_role
  from public.business_members bm
  where bm.business_id = p_business_id
    and bm.user_id = v_user_id
  limit 1;

  if v_role not in ('Owner', 'Manager') then
    raise exception using errcode = '42501', message = 'Only an owner or manager can reject AI actions.';
  end if;

  select *
    into v_action
  from public.ai_action_requests
  where id = p_action_id
    and business_id = p_business_id
  for update;

  if not found then
    raise exception using errcode = 'P0002', message = 'AI action request not found.';
  end if;

  if v_action.status = 'executed' then
    raise exception using errcode = '22023', message = 'An executed AI action cannot be cancelled.';
  end if;

  if v_action.status = 'rejected' then
    return jsonb_build_object(
      'success', true,
      'status', 'rejected',
      'action_id', v_action.id,
      'idempotent_replay', true
    );
  end if;

  if v_action.status not in ('pending', 'approved') then
    raise exception using errcode = '22023', message = 'This AI action cannot be cancelled.';
  end if;

  update public.ai_action_requests
  set status = 'rejected',
      approved_by = v_user_id,
      approved_at = now(),
      error_message = null,
      updated_at = now()
  where id = v_action.id;

  if v_action.message_id is not null then
    update public.ai_messages
    set metadata = jsonb_set(
      jsonb_set(
        coalesce(metadata, '{}'::jsonb),
        '{pending_action,status}',
        to_jsonb('rejected'::text),
        true
      ),
      '{pending_action,error_message}',
      'null'::jsonb,
      true
    )
    where id = v_action.message_id
      and business_id = p_business_id;
  end if;

  insert into public.audit_logs (business_id, user_id, action, details)
  values (
    p_business_id,
    v_user_id,
    'ai_action_rejected',
    jsonb_build_object(
      'ai_action_id', v_action.id,
      'action_type', v_action.action_type
    )
  );

  return jsonb_build_object(
    'success', true,
    'status', 'rejected',
    'action_id', v_action.id,
    'idempotent_replay', false
  );
end;
$$;

revoke all on function public.reject_ai_action_request(uuid, uuid) from public;
grant execute on function public.reject_ai_action_request(uuid, uuid) to authenticated;

commit;
